services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10007:3000
      - 10008:80
    volumes:
      - /data/docker/adguard/work:/opt/adguardhome/work
      - /data/docker/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped