services:
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    container_name: comfyui
    restart: unless-stopped
    devices:
      - nvidia.com/gpu=all
    ports:
      - "10010:10010"
    volumes:
      - /home/chrisleebear/data/docker/comfyui/output:/opt/ComfyUI/output
      - /home/chrisleebear/data/docker/comfyui/input:/opt/ComfyUI/input
      - /home/chrisleebear/data/ai/models:/opt/ComfyUI/models
      - /home/chrisleebear/data/docker/comfyui/user:/opt/ComfyUI/user
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Vienna
      - WEB_ENABLE_AUTH=false
      - COMFYUI_PORT_HOST=10010